flow_task_resource_file_path: ":rails_root/public/attachments/:class/:id/:filename"
flow_task_resource_file_url: "/attachments/:class/:id/:filename"
flow_task_resource_file_size_less_than: 104857600 # 100 megabytes
